#!/bin/bash

if [ "$ENV" = "dev" ]; then
    echo 'enabling xdebug...'

    sed -i 's/^;//' /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    {
        echo "xdebug.mode=debug,develop,coverage"
        echo "xdebug.start_with_request=trigger"
        echo "xdebug.discover_client_host = true"
    } >> /usr/local/etc/php/php.ini
fi