version: '3.8'
services:
  web:
    container_name: server
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - api
    volumes:
      - .:/application
    networks:
      - app-network

  api:
    container_name: api
    image: php_api
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - .:/application
    networks:
      - app-network

  database:
    container_name: database
    image: mysql:5.7
    ports:
      - '33060:3306'
    volumes:
      - ./mysql-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: taskster
      MYSQL_ROOT_PASSWORD: password

networks:
  app-network:
    driver: bridge
